const themecolor = {
  direction: "ltr",
  token: {
    authbgcolor: "#f8fafc",
    colorTextDescription: "#64748b",
    //color
    colorSuccessBg: "#ecfdf5",
    colorInfoBg: "#f0f9ff",
    colorWarningBg: "#fffbeb",
    colorDangerBg: "#fef2f2",
    colorYellowBg: "#fffbeb",
    colorGrayrBg: "#f8fafc",
    colorPurpleBg: "#f5f3ff",
    colorGreenBg: "#dcfce7",
    colorRedBg: "#fee2e2",
    colorLightBlue: "#f0f9ff",
    colorSuccess: "#10b981",
    colorPrimary: "#3b82f6", // Changed to blue
    //text
    textMute: "#64748b",
    sidebarText: "#1e293b",
    textInfo: "#0ea5e9",
    textDark: "#0f172a",
    textLight: "#f8fafc",
    contactBg: "#dbeafe",
    textBlue: "#3b82f6",
    borderGray: "#e2e8f0",
    colorPrimaryBg: "#f1f5f9",
    colorSplit: "rgba(5, 5, 5, 0.06)",
    colorFillTertiary: "rgba(0, 0, 0, 0.04)",
    emailText: "#64748b",
    emailSubText: "#0f172a",
    emailSidebar: "rgba(150, 150, 150, 0.08)",
    emailSidebars: "rgba(150, 150, 150, 0.08)",
    colorBorder: "#e2e8f0",
    colorBgContainer: "#ffffff",
    //tooltips Data Display
    colorBgSpotlight: "rgba(15, 23, 42, 0.85)", // tooltip bg color
    colorTextLightSolid: "#ffffff", // tooltip color
    //Drawer Feedback
    colorBgElevated: "#ffffff", //Drawer bg color
    colorBgMask: "rgba(15, 23, 42, 0.45)", //Drawer overlay bg
    colorIcon: "rgba(15, 23, 42, 0.45)", //Drawer close button color
    colorIconHover: "rgba(15, 23, 42, 0.88)", //Drawer close hover button color
    colorTextTertiary: "rgba(15, 23, 42, 0.45)",
    colorTextSecondary: "#0f172a",
    colorTextLabel: "rgba(15, 23, 42, 0.65)",

    //Spacing and sizes
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    controlOutlineWidth: 2,
    fontSizeIcon: 14,
    fontSize: 14,
    fontSizeHeading1: 38,
    fontSizeHeading2: 30,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    fontSizeLG: 16,
    fontWeightStrong: 600,
    linkDecoration: "none",
    linkHoverDecoration: "none",
    lineType: "solid",
    lineWidth: 1,
    lineWidthBold: 2,
    lineWidthFocus: 4,

    sizePopupArrow: 18,
    zIndexPopupBase: 1000,
    controlPaddingHorizontal: 16,
    controlPaddingHorizontalSM: 12,
    boxShadowTertiary:
      "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
    boxShadowSecondary:
      "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
    screenLGMax: 1199,
    screenMDMax: 991,
    screenSMMax: 767,
    screenXSMax: 575,
    gray: "#64748b",
  },
  components: {
    Menu: {
      headerBgColor: "#ffffff",
      verticalSidebarWidth: 260,
      groupTitleColor: "#64748b",
      itemBg: "#ffffff",
      itemColor: "#64748b",
      itemActiveBg: "#f0f9ff",
      itemHoverBg: "#f0f9ff",
      itemHoverColor: "#3b82f6",
      subMenuItemBg: "#ffffff",
      itemSelectedBg: "#f0f9ff",
      menuBorderColor: "#e2e8f0",
    },
    Typography: {
      titleMarginBottom: "1rem",
      titleMarginTop: "0",
    },
    //navigation
    Anchor: {
      linkPaddingBlock: 4,
      linkPaddingInlineStart: 16,
    },
    Breadcrumb: {
      iconFontSize: 15,
      itemColor: "#94a3b8",
      lastItemColor: "#1e293b",
      linkColor: "#1e293b",
      linkHoverColor: "#3b82f6",
      separatorColor: "#94a3b8",
      separatorMargin: 8,
    },
    Pagination: {
      itemActiveBg: "#ffffff",
      itemActiveBgDisabled: "rgba(0, 0, 0, 0.15)",
      itemActiveColorDisabled: "rgba(0, 0, 0, 0.25)",
      itemBg: "#ffffff",
      itemInputBg: "#ffffff",
      itemLinkBg: "#ffffff",
      itemSize: 32,
      itemSizeSM: 24,
    },
    Steps: {
      customIconFontSize: 24,
      customIconSize: 32,
      customIconTop: 0,
      descriptionMaxWidth: 140,
      dotCurrentSize: 10,
      dotSize: 8,
      iconFontSize: 14,
      iconSize: 32,
      iconSizeSM: 24,
      iconTop: -0.5,
      navArrowColor: "rgba(0, 0, 0, 0.25)",
      navContentMaxWidth: "auto",
      titleLineHeight: 32,
    },
    //Data Entry
    AutoComplete: {
      zIndexPopup: 1050,
    },
    Cascader: {
      controlItemWidth: 111,
      controlWidth: 184,
      dropdownHeight: 180,
    },
    DatePicker: {
      presetsMaxWidth: 200,
      presetsWidth: 120,
      zIndexPopup: 1050,
    },
    InputNumber: {
      controlWidth: 90,
      handleFontSize: 7,
      handleVisible: "auto",
      handleWidth: 22,
    },
    Mentions: {
      controlItemWidth: 100,
      dropdownHeight: 250,
      zIndexPopup: 1050,
    },
    Radio: {
      buttonBg: "#ffffff",
      buttonCheckedBg: "#ffffff",
      buttonCheckedBgDisabled: "rgba(0, 0, 0, 0.1)",
      buttonCheckedColorDisabled: "rgba(0, 0, 0, 0.50)",
      buttonColor: "rgba(0, 0, 0, 0.88)",
      buttonPaddingInline: 15,
      buttonSolidCheckedColor: "#fff",
      dotColorDisabled: "rgba(0, 0, 0, 0.25)",
      dotSize: 8,
      radioSize: 16,
      wrapperMarginInlineEnd: 8,
    },
    Select: {
      zIndexPopup: 1050,
    },
    Slider: {
      controlSize: 20,
      dotSize: 8,
      handleLineWidth: 2,
      handleLineWidthHover: 4,
      handleSize: 10,
      handleSizeHover: 12,
      railSize: 4,
    },
    TimePicker: {
      presetsMaxWidth: 200,
      presetsWidth: 120,
      zIndexPopup: 1050,
    },
    Transfer: {
      headerHeight: 40,
      itemHeight: 32,
      itemPaddingBlock: 8,
      listHeight: 200,
      listWidth: 180,
      listWidthLG: 250,
    },
    //Data Display
    Avatar: {
      groupBorderColor: "#ffffff",
    },
    Calendar: {
      fullBg: "#ffffff",
      fullPanelBg: "#ffffff",
      miniContentHeight: 256,
      monthControlWidth: 80,
      yearControlWidth: 90,
    },
    Card: {
      actionsBg: "#ffffff",
      actionsLiMargin: "12px 0",
      headerFontSize: 16,
      headerFontSizeSM: 14,
      headerHeight: 55,
      headerHeightSM: 38,
      tabsMarginBottom: -25,
    },
    Carousel: {
      dotActiveWidth: 24,
      dotHeight: 3,
      dotWidth: 16,
    },
    Descriptions: {
      colonMarginLeft: 2,
      colonMarginRight: 8,
      extraColor: "rgba(0, 0, 0, 0.88)",
      itemPaddingBottom: 16,
      labelBg: "rgba(0, 0, 0, 0.02)",
      titleMarginBottom: 20,
    },
    List: {
      avatarMarginRight: 14,
      contentWidth: 220,
      descriptionFontSize: 14,
      emptyTextPadding: 16,
      footerBg: "transparent",
      headerBg: "transparent",
      itemPadding: "12px 0",
      itemPaddingLG: "16px 24px",
      itemPaddingSM: "8px 16px",
      metaMarginBottom: 16,
      titleMarginBottom: 10,
    },
    Popover: {
      zIndexPopup: 1030,
    },
    Segmented: {
      itemActiveBg: "rgba(0, 0, 0, 0.15)",
      itemColor: "#64748b",
      itemHoverBg: "rgba(0, 0, 0, 0.02)",
      itemHoverColor: "#0f172a",
      itemSelectedBg: "#ffffff",
    },
    Statistic: {
      contentFontSize: 22,
      titleFontSize: 15,
    },
    Tabs: {
      cardBg: "#f1f5f9",
      cardGutter: 4,
      cardHeight: 40,
      cardPadding: "8px 16px",
      cardPaddingLG: "8px 16px 6px",
      cardPaddingSM: "6px 16px",
      horizontalItemGutter: 25,
      horizontalItemPadding: "12px 0",
      horizontalItemPaddingLG: "16px 0",
      horizontalItemPaddingSM: "8px 0",
      horizontalMargin: "0 0 16px 0",
      titleFontSize: 15,
      titleFontSizeLG: 16,
      titleFontSizeSM: 14,
      verticalItemMargin: "16px 0 0 0",
      zIndexPopup: 1050,
    },
    Tag: {
      defaultBg: "#f1f5f9",
      defaultColor: "#0f172a",
    },
    Timeline: {
      itemPaddingBottom: 12,
      dotBorderWidth: 2,
      tailColor: "#e2e8f0",
      tailWidth: 2,
    },
    Tooltip: {
      zIndexPopup: 1070,
    },
    Tree: {
      headerHeight: 40,
      itemHeight: 180,
      itemPaddingBlock: 5,
      listHeight: 200,
      listWidth: 180,
      listWidthLG: 250,
    },
    //Feedback
    Drawer: {
      footerPaddingBlock: 8,
      footerPaddingInline: 16,
      zIndexPopup: 1000,
    },
    Message: {
      contentBg: "#ffffff",
      contentPadding: "10px 16px",
      zIndexPopup: "1010",
    },
    Modal: {
      contentBg: "#ffffff",
      footerBg: "#ffffff",
      headerBg: "#ffffff",
      titleColor: "rgba(0, 0, 0, 0.88)",
      titleFontSize: 16,
      titleLineHeight: 1.5,
    },
    Notification: {
      width: 384,
      zIndexPopup: 1050,
    },
    Popconfirm: {
      zIndexPopup: 1060,
    },
    Result: {
      extraMargin: "24px 0 0 0", //result-extra margin
      iconFontSize: 55,
      subtitleFontSize: 15,
      titleFontSize: 24,
    },
    Spin: {
      contentHeight: 400,
    },
  },
};

// Theme colors specific to dark theme
const darkthemecolors = {
  token: {
    authbgcolor: "#0f172a",
    colorTextDescription: "#94a3b8",
    //color
    colorSuccessBg: "#064e3b",
    colorInfoBg: "#0c4a6e",
    colorWarningBg: "#713f12",
    colorDangerBg: "#7f1d1d",
    colorYellowBg: "#713f12",
    colorRedBg: "#7f1d1d",
    colorPurpleBg: "#4c1d95",
    colorGreenBg: "#064e3b",
    colorLightBlue: "#0c4a6e",
    colorSuccess: "#10b981",
    colorPrimary: "#3b82f6", // Changed to blue

    //text
    textMute: "#94a3b8",
    sidebarText: "#94a3b8",
    textInfo: "#ffffff",
    textDark: "#0ea5e9",
    textLight: "#ffffff",
    contactBg: "#1e3a8a",
    textBlue: "#3b82f6",

    borderGray: "#1e293b",
    colorPrimaryBg: "#1e293b",
    emailText: "#ffffff",
    emailSubText: "#ffffff",
    emailSidebar: "#0f172a",
    emailSidebars: "#0f172a",

    colorBgContainer: "#1e293b",
    colorBgLayout: "#0f172a",
    colorText: "#FFFFFF",
    colorTextHeading: "#e2e8f0",
    colorBorder: "#1e293b",
    colorBorderSecondary: "#1e293b",
    colorTextTertiary: "#94a3b8",
    colorTextPlaceholder: "#94a3b8",
    fontFamily: '"Inter", sans-serif',
    textMuted: "#ffffff",
    colorBgElevated: "#0f172a",
    nonauthBg: "#0f172a",
    colorBgContainerDisabled: "#1e293b",
    colorFill: "#1e293b", // skeleton overlay bg
    colorFillContent: "#334155", // skeleton bg
    colorFillSecondary: "#334155", // progress's bar bg
    colorSplit: "#1e293b",
    colorFillTertiary: "#1e293b",
    colorBgSpotlight: "#1e293b", // tooltip bg color
    colorTextQuaternary: "#1e293b",
    colorTextSecondary: "#e2e8f0",
    colorTextLabel: "#94a3b8",
  },
  components: {
    Layout: {
      bodyBg: "#0f172a",
      headerBg: "#1e293b",
      colorBgTrigger: "#94a3b8",
    },
    Menu: {
      groupTitleColor: "#94a3b8",
      itemBg: "#1e293b",
      itemColor: "#94a3b8",
      itemActiveBg: "#3b82f61a",
      itemHoverBg: "#3b82f61a",
      itemHoverColor: "#3b82f6",
      subMenuItemBg: "#1e293b",
      itemSelectedBg: "#3b82f61a",
      menuBorderColor: "#1e293b",
    },
    Breadcrumb: {
      iconFontSize: 15,
    },
    Tabs: {
      cardBg: "#f5f5f5",
      cardGutter: 4,
      cardHeight: 40,
      cardPadding: "8px 16px",
      cardPaddingLG: "8px 16px 6px",
      cardPaddingSM: "6px 16px",
      horizontalItemGutter: 25,
      horizontalItemPadding: "12px 0",
      horizontalItemPaddingLG: "16px 0",
      horizontalItemPaddingSM: "8px 0",
      horizontalMargin: "0 0 16px 0",
      titleFontSize: 15,
      titleFontSizeLG: 16,
      titleFontSizeSM: 14,
      verticalItemMargin: "16px 0 0 0",
      zIndexPopup: 1050,
    },
    Radio: {
      buttonBg: "#1e293b",
      buttonCheckedBg: "#1e293b",
      buttonCheckedBgDisabled: "#334155",
      buttonCheckedColorDisabled: "#94a3b8",
      buttonColor: "#e2e8f0",
      buttonPaddingInline: 15,
      buttonSolidCheckedColor: "#fff",
      dotColorDisabled: "#94a3b8",
      dotSize: 8,
      radioSize: 16,
      wrapperMarginInlineEnd: 8,
    },
  },
};

const customStyle = {
  token: {
    //Spacing and sizes
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    controlOutlineWidth: 2,
    fontSizeIcon: 14,
    fontSize: 14,
    fontSizeHeading1: 38,
    fontSizeHeading2: 30,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    fontSizeLG: 16,
    fontWeightStrong: 600,
    linkDecoration: "none",
    linkHoverDecoration: "none",
    lineType: "solid",
    lineWidth: 1,
    lineWidthBold: 2,
    lineWidthFocus: 4,
    sizePopupArrow: 18,
    zIndexPopupBase: 1000,
    controlPaddingHorizontal: 16,
    controlPaddingHorizontalSM: 12,
    screenLGMax: 1199,
    screenMDMax: 991,
    screenSMMax: 767,
    screenXSMax: 575,

    margin: 24,
    marginSM: 20,
    marginXS: 14,
    marginXXS: 4,
    borderRadiusXS: 4,
    borderRadiusSM: 6,
    borderRadius: 8,
    borderRadiusLG: 12,
    padding: 16,
    paddingLG: 22,
    paddingSM: 12,
    paddingXS: 8,
    paddingXXS: 4,

    //colors Palette
    nonauthBg: "#f8fafc",
    colorBgContainer: "#fff",
    colorBgContainerDisabled: "rgba(0, 0, 0, 0.04)",
    colorBgLayout: "#f1f5f9",
    colorText: "#0f172a",
    colorTextDisabled: "#94a3b8",
    colorTextPlaceholder: "#94a3b8",
    colorTextQuaternary: "rgba(15, 23, 42, 0.45)",
    colorTextHeading: "rgba(15, 23, 42, 0.88)",
    fontFamily: '"Inter", sans-serif',
    colorFillAlter: "rgba(15, 23, 42, 0.02)",
    colorFill: "rgba(15, 23, 42, 0.15)", // skeleton overlay bg
    colorFillContent: "rgba(15, 23, 42, 0.06)", // skeleton bg
    colorFillQuaternary: "rgba(15, 23, 42, 0.02)",
    colorFillSecondary: "rgba(15, 23, 42, 0.06)", // progress's bar bg
    colorHighlight: "#ef4444",
    colorBorderSecondary: "#f1f5f9",
    colorError: "#ef4444",
    colorSuccess: "#10b981",
    colorGreenBg: "#dcfce7",
    colorSuccessBg: "#ecfdf5",
    colorPrimary: "#3b82f6", // Changed to blue
    colorPrimaryBg: "rgba(59, 130, 246, 0.10)",
    colorInfo: "#0ea5e9",
    colorInfoBg: "#f0f9ff",
    colorDanger: "#ef4444",
    colorDangerBg: "#fee2e2",
    textMuted: "#64748b",
    colorWarning: "#f59e0b",
    colorWarningBg: "#fffbeb",
    colorTextCode: "#ec4899",
    colorLink: "#3b82f6", // Changed to blue
    colorLinkActive: "#60a5fa", // Changed to light blue
    colorDark: "#0f172a",
    colorDarkBg: "#f1f5f9",
    colorLinkHover: "#60a5fa", // Changed to light blue
    controlItemBgHover: "rgba(15, 23, 42, 0.04)",
    bglight: "#0f172a",
    colorSecondary: "#4f46e5",
    colorSecondaryBg: "#f5f3ff",

    // heading
    h1: 34,
    h2: 30,
    h3: 24,
    h4: 20,
    h5: 18,
    h6: 16,
  },
};

export { themecolor, darkthemecolors, customStyle };